---
- name: create temp directory
  tempfile:
    state: directory
    suffix: network
  register: temp_dir

- include_tasks: task-defaults.yml
  vars:
    service_name: defaults

- include_tasks: "task-service.yml"
  vars:
    service_name: "{{ item }}"
  with_items:
    - cache
    - messaging
    - scylladb
    - db
    # - dashboard

- include_tasks: task-service.yml
  vars:
    service_name: services
