version: "3.8"

services:
  db:
    container_name: "db"
    image: "postgis/postgis:15-3.3"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: db
    restart: unless-stopped
