version: "3.8"

services:
  db:
    container_name: {{ service_name }}
    image: {{ images.db }}
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      OTEL_EXPORTER_OTLP_ENDPOINT: {{ otlp_endpoint }}
      OTEL_SERVICE_NAME: {{ service_name }}
    restart: unless-stopped
    # ports:
    #   - target: 5432
    #     published: 5432
