version: "3.8"

volumes:
  db:

networks:
  default:
    name: {{ stack_network }}
    external: true

services:
  db:
    container_name: {{ service_name }}
    image: {{ images.db }}
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      OTEL_EXPORTER_OTLP_ENDPOINT: {{ otlp_endpoint }}
      OTEL_SERVICE_NAME: {{ service_name }}
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    networks:
      - default
    # ports:
    #   - target: 5432
    #     published: 5432
