x-app: &app
  restart: unless-stopped
  environment: &app-env
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    MessagingUser: {{ messaging.username }}
    MessagingPass: {{ messaging.password }}
    DbUser: {{ db.username }}
    DbPass: {{ db.password }}
    CassandraHost: {{ scylladb.host }}
    CassandraPort: {{ scylladb.port }}
    CassandraUser: {{ scylladb.username }}
    CassandraPass: {{ scylladb.password }}
    ConnectionStrings__cache: {{ ConnectionStrings.cache }}
    ConnectionStrings__messaging: {{ ConnectionStrings.messaging }}
    ConnectionStrings__trace: {{ ConnectionStrings.db }}
    OTEL_EXPORTER_OTLP_ENDPOINT: {{ otlp_endpoint }}
    services__geocoding: "https://nominatim.openstreetmap.org"
    services__routing: "https://valhalla.openstreetmap.de"
    services__service-gateway__0: "http://service-gateway:8080"
    services__service-gateway__1: "https://service-gateway:8443"
    services__service-core__0: "http://service-core:8080"
    services__service-core__1: "https://service-core:8443"
    services__service-integration__0: "http://service-integration:8080"
    services__service-integration__1: "https://service-integration:8443"
    services__service-navigation__0: "http://service-navigation:8080"
    services__service-navigation__1: "https://service-navigation:8443"

version: "3.8"

networks:
  default:
    name: {{ stack_network }}
    external: true

services:
  service-core:
    <<: *app
    container_name: "service-core"
    image: "{{ registry }}/trace-service-core:{{ version }}"
    environment:
      <<: *app-env
      OTEL_SERVICE_NAME: service-core
    restart: unless-stopped
    ports:
      - target: 8080
        published: 10000

  service-integration:
    <<: *app
    container_name: service-integration
    image: "{{ registry }}/trace-service-integration:{{ version }}"
    environment:
      <<: *app-env
      OTEL_SERVICE_NAME: service-integration
    restart: unless-stopped
    ports:
      - target: 8080
        published: 10002

  service-navigation:
    <<: *app
    container_name: service-navigation
    image: "{{ registry }}/trace-service-navigation:{{ version }}"
    environment:
      <<: *app-env
      OTEL_SERVICE_NAME: service-navigation
    restart: unless-stopped
    ports:
      - target: 8080
        published: 10004

  service-gateway:
    <<: *app
    container_name: service-gateway
    image: "{{ registry }}/trace-service-gateway:{{ version }}"
    environment:
      <<: *app-env
      OTEL_SERVICE_NAME: service-gateway
    restart: unless-stopped
    ports:
      - target: 8080
        published: 10006

  frontend:
    <<: *app
    container_name: frontend
    image: "{{ registry }}/trace-frontend:{{ version }}"
    environment:
      <<: *app-env
      OTEL_SERVICE_NAME: frontend
    restart: unless-stopped
    ports:
    - target: 8080
      published: 10008

  website:
    container_name: website
    image: "{{ registry }}/trace-website:{{ version }}"
    environment:
      <<: *app-env
      OTEL_SERVICE_NAME: website
    restart: unless-stopped
    restart: unless-stopped
    ports:
      - target: 8080
        published: 10010

  manager:
    <<: *app
    container_name: manager
    image: "{{ registry }}/trace-manager:{{ version }}"
    environment:
      <<: *app-env
      OTEL_SERVICE_NAME: manager
    restart: unless-stopped
    ports:
    - target: 8080
      published: 10012
