version: "3.8"

services:
  messaging:
    container_name: "messaging"
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
    restart: unless-stopped
