x-app: &app
  restart: unless-stopped
  environment: &app-env
    ASPNETCORE_URLS: "http://+:8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    MessagingUser: "guest"
    MessagingPass: "guest"
    DbUser: "postgres"
    DbPass: "postgres"
    CassandraPort: 9042
    CassandraUser: "cassandra"
    CassandraPass: "cassandra"
    ConnectionStrings__cache: "cache:6379,abortConnect=false,AllowAdmin=true"
    ConnectionStrings__messaging: "amqp://guest:guest@messaging:5672"
    ConnectionStrings__trace: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=trace"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
    services__geocoding: "https://nominatim.openstreetmap.org"
    services__routing: "https://valhalla.openstreetmap.de"
    services__service-gateway__0: "http://service-gateway:8080"
    services__service-gateway__1: "https://service-gateway:8443"
    services__service-core__0: "http://service-core:8080"
    services__service-core__1: "https://service-core:8443"
    services__service-integration__0: "http://service-integration:8080"
    services__service-integration__1: "https://service-integration:8443"
    services__service-navigation__0: "http://service-navigation:8080"
    services__service-navigation__1: "https://service-navigation:8443"

version: "3.8"

networks:
  default:
    name: trace_staging
    external: true

services:
  service-core:
    <<: *app
    container_name: "service-core"
    image: ${REGISTRY}/trace-service-core:${VERSION}
    environment:
      <<: *app-env
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001


  service-integration:
    <<: *app
    container_name: service-integration
    image: ${REGISTRY}/trace-service-integration:${VERSION}
    environment:
      <<: *app-env
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003


  service-navigation:
    <<: *app
    container_name: service-navigation
    image: ${REGISTRY}/trace-service-navigation:${VERSION}
    environment:
      <<: *app-env
    ports:
    - target: 8080
      published: 10004
    - target: 8443
      published: 10005


  service-gateway:
    <<: *app
    container_name: service-gateway
    image: ${REGISTRY}/trace-service-gateway:${VERSION}
    environment:
      <<: *app-env
    ports:
    - target: 8080
      published: 10006
    - target: 8443
      published: 10007


  frontend:
    <<: *app
    container_name: frontend
    image: ${REGISTRY}/trace-frontend:${VERSION}
    environment:
      <<: *app-env
    ports:
    - target: 8080
      published: 10008
    - target: 8443
      published: 10009


  manager:
    <<: *app
    container_name: manager
    image: ${REGISTRY}/manager:${VERSION}
    environment:
      <<: *app-env
    ports:
    - target: 8080
      published: 10010
    - target: 8443
      published: 10011

