version: "3.8"

services:
  warehouse:
    container_name: "warehouse"
    image: "scylladb/scylla:5.4"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    restart: unless-stopped
